remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme 
title: Omeka S Installation with Docker Tutorial
description: A guide on installing and using Omeka S in a Docker container
navigation:
  - title: "Introduction"
    url: /
  - title: "Installation"
    url: /installation/
  - title: "Linux"
    url: /Installation/Linux
  - title: "MacOS"
    url: /Installation/MacOS

