theme: jekyll-theme-minimal
title: Omeka S Installation with Docker Tutorial
description: A guide on installing and using Omeka S in a Docker container
navigation:
  - title: "Home"
    url: /
  - title: "Installation"
    url: /installation/
  - title: "Usage"
    url: /usage/
  - title: "FAQ"
    url: /faq/

